### PR TITLE
methods of `NM.Client` requires the object instance as first argument

### PR DESCRIPTION
**Pull request by shnurty**
In 'protonvpn.log' file, I've spotted a caught exception for 
`(callback_type_dict[callback_type]["finish_function"])`
inside `__dynamic_callback` in "core/connection_backend/nm_client/nm_client_mixin.py".

This is caused by the missing object instance parameter in argument list for the above function
which, as instance method, expects to be called on an object instance.

### CODE REVIEW

**Comment by shnurty** [comment]
I'm sorry, I forgot the exception log:

```
... nm_client_mixin.py — ERROR — __dynamic_callback:124 — Exception: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protonvpn_nm_lib/core/connection_backend/nm_client/nm_client_mixin.py", line 117, in __dynamic_callback
    (callback_type_dict[callback_type]["finish_function"])(result)
TypeError: NM.Client.add_connection_finish() takes exactly 2 arguments (1 given
```

**Comment by calexandru2018** [comment]
hey @shnurty could you please rebase to resolved the conflicts ?

**Comment by shnurty** [comment]
hey @calexandru2018 , sorry for the delay.
I've imported the new changes were made to the master, now is fine.

PS: sorry for the space removal, please let me know if you want me to revert them also
the only real change is always in `nm_client_mixin.py`

**Comment by calexandru2018** [comment]
Hey @shnurty 

Your MR has been merged internally into our repo. Once we make a new release, your fix will also be deployed.

**Pull request closed without merging**
